[book]
authors = ["TeamFlos"]
language = "zh-CN"
multilingual = false
src = "src"
title = "Phira Documents"

[build]
extra-watch-dirs = ["po"]

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 1         # the depth to start folding

[preprocessor.gettext]
after = ["links"]
