[book]
authors = ["TeamFlos"]
language = "zh-CN"
multilingual = false
src = "src"
title = "Phira Documents"

[output.html.fold]
enable = true    # whether or not to enable section folding
level = 1         # the depth to start folding